import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync, readdirSync, statSync, openSync, closeSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const OBSIDIAN_PLUGIN_PATH = "H:/Docs/Obsinote/.obsidian/plugins/vault-sniffer";

function copyDirectory(src, dest) {
	if (!existsSync(dest)) {
		mkdirSync(dest, { recursive: true });
	}

	const entries = readdirSync(src, { withFileTypes: true });

	for (let entry of entries) {
		const srcPath = join(src, entry.name);
		const destPath = join(dest, entry.name);

		if (entry.isDirectory()) {
			copyDirectory(srcPath, destPath);
		} else {
			copyFileSync(srcPath, destPath);
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
});

if (prod) {
	await context.rebuild();
	// Copy required files to dist/
	if (!existsSync("dist")) {
		mkdirSync("dist", { recursive: true });
	}
	copyFileSync("manifest.json", "dist/manifest.json");
	copyFileSync("styles.css", "dist/styles.css");
	console.log("Copied manifest.json and styles.css to dist/");

	// Copy dist to Obsidian plugin directory
	copyDirectory("dist", OBSIDIAN_PLUGIN_PATH);
	console.log(`Copied dist files to ${OBSIDIAN_PLUGIN_PATH}`);

	// Create .hotreload file if it doesn't exist
	const hotreloadPath = join(OBSIDIAN_PLUGIN_PATH, ".hotreload");
	if (!existsSync(hotreloadPath)) {
		const fd = openSync(hotreloadPath, "w");
		closeSync(fd);
		console.log("Created .hotreload file");
	}

	process.exit(0);
} else {
	await context.watch();
}
